title: Api wilayah indonesia | whdzera
email: whdzera@gmail.com
baseurl: "/jekyll-api-wilayah-indonesia" 
url: "" 
twitter_username: whdzera
github_username:  rokhimin/jekyll-api-wilayah-indonesia

permalink: /:title.rb
files: "/jekyll-api-wilayah-indonesia"